
export const SHOP_PERMISSIONS = [
	"SELL",
	"MANAGE_PRODUCTS",
	"MANAGE_INVENTORY",
	"VIEW_STATS",
	"MANAGE_SETTINGS",
	"MANAGE_EVENTS",
	"MANAGE_EXPENSES",
] as const;

export type ShopPermission = typeof SHOP_PERMISSIONS[number];

export const SHOP_PERM = {
    SELL: "SELL",
    MANAGE_PRODUCTS: "MANAGE_PRODUCTS",
    MANAGE_INVENTORY: "MANAGE_INVENTORY",
    VIEW_STATS: "VIEW_STATS",
    MANAGE_SETTINGS: "MANAGE_SETTINGS",
    MANAGE_EVENTS: "MANAGE_EVENTS",
    MANAGE_EXPENSES: "MANAGE_EXPENSES",
} as const;
